version: '3'
services:
    api:
        build: .
        ports:
            - '8080:8080'
        volumes:
            - .:/app
        env_file:
            - .env
        depends_on:
        - pgdb
        networks:
            - default
    pgdb:
        image: postgres:14-alpine
        container_name: pgdb
        restart: always
        env_file:
        - .env
        environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
        ports:
        - "5432:5432"
        volumes:
        - postgres-db:/var/lib/postgresql/data
        networks:
            - default
volumes:
  postgres-db:

networks:
  default:
    driver: bridge

