version: '3'

services:
    rediscache:
        container_name: rediscache
        image: redis
        restart: always
        ports:
            - 6379:6379
    api:
        container_name: api
        hostname: api
        build: .
        ports:
            - 8080:8080
        volumes:
            - .:/usr/app
        env_file:
            - .env
        depends_on:
            - rediscache
