version: '3'
services:
    api:
        build: .
        ports:
            - '8080:8080'
        volumes:
            - .:/app
        environment:
            - PORT=8080
            - NODE_ENV=development
        networks:
            - default
    db:
        image: 'postgres:13-alpine'
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=pgdocker
        volumes:
            - ./data:/var/lib/postgresql/data
        networks:
            - default

networks:
    default:
        driver: bridge
