version: '3.8'
services:
    pgdocker:
        container_name: pgdocker
        hostname: pgdocker
        restart: always
        image: postgres:14-alpine
        env_file:
            - .env
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        ports:
            - 5432:5432
        volumes:
            - pg-db:/var/lib/postgresql/data
    rediscache:
        container_name: rediscache
        image: redis:alpine
        ports:
            - 6379:6379
    api:
        container_name: api
        hostname: api
        build: .
        ports:
            - 8080:8080
        volumes:
            - .:/usr/app
        env_file:
            - .env
        depends_on:
            - pgdocker
            - rediscache
volumes:
    pg-db:
