version: '3.8'
services:
    pg:
        image: postgres:14
        env_file:
            - .env
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        ports:
            - 5432:5432
        volumes:
            - pg-db:/var/lib/postgresql/data
        networks:
            - flexnet
    rediscache:
        image: redis:alpine
        ports:
            - 6379:6379
        networks:
            - flexnet
    api:
        build: .
        ports:
            - 8080:8080
        volumes:
            - .:/usr/app
        env_file:
            - .env
        depends_on:
            - pg
            - rediscache
        networks:
            - flexnet
volumes:
    pg-db:

networks:
    flexnet:
        driver: bridge
